@startuml

package "Client Logic" {
  [Entry Point] as ClientEntryPoint
  package "Store" {
    [Client Middleware] as ClientMiddleware
    [Connection] as ClientConnection
    () "WebSocket"

    ClientMiddleware -> ClientConnection
    ClientConnection --> WebSocket
  }
  package "View" {
    () "react-redux" as ReactRedux
    [Renderer]
    Store ...> ReactRedux
    ReactRedux -> Renderer
  }
  ClientEntryPoint .left.> Renderer
  ClientEntryPoint ...> Store
}

package "Game Logic" {
  [Reducer]
  [Middleware]
}

package "Server Logic" {
  [Entry Point] as ServerEntryPoint
}

@enduml
